<?xml version="1.0" encoding="iso-8859-1"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output method="text" encoding="iso-8859-1"/>
	<xsl:template match="/">
		<xsl:value-of select="FC_FeatureCatalogue/name"/>&#13;&#10;Version: <xsl:value-of select="FC_FeatureCatalogue/versionNumber"/>&#13;&#10;Stand: <xsl:value-of select="FC_FeatureCatalogue/versionDate"/>&#13;&#10;Modellarten: <xsl:for-each select="FC_FeatureCatalogue/modellart"><xsl:value-of select="."/><xsl:text> </xsl:text></xsl:for-each>&#13;&#10;&#13;&#10;Objektart;Kennung;Modellart;Grunddatenbestand;Profil;Stillgelegt;Objektkategorie;Objekttyp;Nutzungsart;Nutzungsartkennung;Revisionsnummer;Attributart;Kennung;Modellart;Grunddatenbestand;Profil;Stillgelegt;Kardinalit‰t;Typ;Revisionsnummer;Werteart;Kennung;Modellart;Grunddatenbestand;Profil;Stillgelegt;Nutzungsartkennung;Revisionsnummer;Relationsart;Kennung;Modellart;Grunddatenbestand;Profil;Stillgelegt;Kardinalit‰t;Typ;Revisionsnummer;&#13;&#10;<xsl:for-each select="FC_FeatureCatalogue/AC_Objektartengruppe">
			<xsl:sort select="./code"/>
			<xsl:variable name="objektart" select="."/>
			<xsl:if test="count(/FC_FeatureCatalogue/AC_FeatureType/Objektartengruppenzugehoerigkeit[attribute::idref=$objektart/@id]) >= 1">
				<xsl:for-each select="/FC_FeatureCatalogue/AC_FeatureType/Objektartengruppenzugehoerigkeit[attribute::idref=$objektart/@id]">
					<xsl:sort select="../code"/>
					<xsl:variable name="featuretype" select=".."/>
					<xsl:variable name="oa" select="$featuretype/name"/>
					<xsl:if test="count(/FC_FeatureCatalogue/FC_RelationshipRole[attribute::id=$featuretype/characterizedBy/@idref]) + count(/FC_FeatureCatalogue/FC_FeatureAttribute[attribute::id=$featuretype/characterizedBy/@idref]) = 0"><xsl:value-of select="$featuretype/name"/>;<xsl:value-of select="$featuretype/code"/>;<xsl:for-each select="$featuretype/modellart"><xsl:value-of select="."/><xsl:text> </xsl:text></xsl:for-each>;<xsl:for-each select="$featuretype/grunddatenbestand"><xsl:value-of select="."/><xsl:text> </xsl:text></xsl:for-each>;<xsl:for-each select="$featuretype/profil"><xsl:value-of select="."/><xsl:text> </xsl:text></xsl:for-each>;<xsl:if test="$featuretype/retired"><xsl:choose><xsl:when test="$featuretype/taggedValue[@tag='AAA:GueltigBis']"><xsl:value-of select="$featuretype/taggedValue[@tag='AAA:GueltigBis'][1]"/></xsl:when><xsl:otherwise><xsl:text>Ja</xsl:text></xsl:otherwise></xsl:choose></xsl:if>;<xsl:value-of select="$featuretype/bedeutung"/>;<xsl:value-of select="$featuretype/wirdTypisiertDurch"/>;<xsl:value-of select="$featuretype/nutzungsart"/>;<xsl:value-of select="$featuretype/nutzungsartkennung"/>;<xsl:value-of select="$featuretype/letzteAenderungRevisionsnummer"/>;&#13;&#10;</xsl:if>					
					<xsl:if test="count(/FC_FeatureCatalogue/FC_FeatureAttribute[attribute::id=$featuretype/characterizedBy/@idref]) >= 1">
						<xsl:for-each select="/FC_FeatureCatalogue/FC_FeatureAttribute[attribute::id=$featuretype/characterizedBy/@idref]">
							<xsl:variable name="featureAtt" select="."/>
							<xsl:choose>
								<xsl:when test="$featureAtt/ValueDomainType = 1">
									<xsl:for-each select="/FC_FeatureCatalogue/FC_Value[attribute::id=$featureAtt/enumeratedBy/@idref]"><xsl:value-of select="$featuretype/name"/>;<xsl:value-of select="$featuretype/code"/>;<xsl:for-each select="$featuretype/modellart"><xsl:value-of select="."/><xsl:text> </xsl:text></xsl:for-each>;<xsl:for-each select="$featuretype/grunddatenbestand"><xsl:value-of select="."/><xsl:text> </xsl:text></xsl:for-each>;<xsl:for-each select="$featuretype/profil"><xsl:value-of select="."/><xsl:text> </xsl:text></xsl:for-each>;<xsl:if test="$featuretype/retired"><xsl:choose><xsl:when test="$featuretype/taggedValue[@tag='AAA:GueltigBis']"><xsl:value-of select="$featuretype/taggedValue[@tag='AAA:GueltigBis'][1]"/></xsl:when><xsl:otherwise><xsl:text>Ja</xsl:text></xsl:otherwise></xsl:choose></xsl:if>;<xsl:value-of select="$featuretype/bedeutung"/>;<xsl:value-of select="$featuretype/wirdTypisiertDurch"/>;<xsl:value-of select="$featuretype/nutzungsart"/>;<xsl:value-of select="$featuretype/nutzungsartkennung"/>;<xsl:value-of select="$featuretype/letzteAenderungRevisionsnummer"/>;<xsl:value-of select="$featureAtt/name"/>;<xsl:value-of select="$featureAtt/code"/>;<xsl:for-each select="$featureAtt/modellart"><xsl:value-of select="."/><xsl:text> </xsl:text></xsl:for-each>;<xsl:for-each select="$featureAtt/grunddatenbestand"><xsl:value-of select="."/><xsl:text> </xsl:text></xsl:for-each>;<xsl:for-each select="$featureAtt/profil"><xsl:value-of select="."/><xsl:text> </xsl:text></xsl:for-each>;<xsl:if test="$featureAtt/retired"><xsl:choose><xsl:when test="$featureAtt/taggedValue[@tag='AAA:GueltigBis']"><xsl:value-of select="$featureAtt/taggedValue[@tag='AAA:GueltigBis'][1]"/></xsl:when><xsl:otherwise><xsl:text>Ja</xsl:text></xsl:otherwise></xsl:choose></xsl:if>;<xsl:value-of select="$featureAtt/cardinality"/>;<xsl:value-of select="$featureAtt/ValueDataType"/>;<xsl:value-of select="$featureAtt/letzteAenderungRevisionsnummer"/>;<xsl:value-of select="./label"/>;<xsl:value-of select="./code"/>;<xsl:for-each select="./modellart"><xsl:value-of select="."/><xsl:text> </xsl:text></xsl:for-each>;<xsl:for-each select="./grunddatenbestand"><xsl:value-of select="."/><xsl:text> </xsl:text></xsl:for-each>;<xsl:for-each select="./profil"><xsl:value-of select="."/><xsl:text> </xsl:text></xsl:for-each>;<xsl:if test="./retired"><xsl:choose><xsl:when test="./taggedValue[@tag='AAA:GueltigBis']"><xsl:value-of select="./taggedValue[@tag='AAA:GueltigBis'][1]"/></xsl:when><xsl:otherwise><xsl:text>Ja</xsl:text></xsl:otherwise></xsl:choose></xsl:if>;<xsl:value-of select="./nutzungsartkennung"/>;<xsl:value-of select="./letzteAenderungRevisionsnummer"/>;&#13;&#10;</xsl:for-each>
								</xsl:when>
								<xsl:otherwise><xsl:value-of select="$featuretype/name"/>;<xsl:value-of select="$featuretype/code"/>;<xsl:for-each select="$featuretype/modellart"><xsl:value-of select="."/><xsl:text> </xsl:text></xsl:for-each>;<xsl:for-each select="$featuretype/grunddatenbestand"><xsl:value-of select="."/><xsl:text> </xsl:text></xsl:for-each>;<xsl:for-each select="$featuretype/profil"><xsl:value-of select="."/><xsl:text> </xsl:text></xsl:for-each>;<xsl:if test="$featuretype/retired"><xsl:choose><xsl:when test="$featuretype/taggedValue[@tag='AAA:GueltigBis']"><xsl:value-of select="$featuretype/taggedValue[@tag='AAA:GueltigBis'][1]"/></xsl:when><xsl:otherwise><xsl:text>Ja</xsl:text></xsl:otherwise></xsl:choose></xsl:if>;<xsl:value-of select="$featuretype/bedeutung"/>;<xsl:value-of select="$featuretype/wirdTypisiertDurch"/>;<xsl:value-of select="$featuretype/nutzungsart"/>;<xsl:value-of select="$featuretype/nutzungsartkennung"/>;<xsl:value-of select="$featuretype/letzteAenderungRevisionsnummer"/>;<xsl:value-of select="$featureAtt/name"/>;<xsl:value-of select="$featureAtt/code"/>;<xsl:for-each select="$featureAtt/modellart"><xsl:value-of select="."/><xsl:text> </xsl:text></xsl:for-each>;<xsl:for-each select="$featureAtt/grunddatenbestand"><xsl:value-of select="."/><xsl:text> </xsl:text></xsl:for-each>;<xsl:for-each select="$featureAtt/profil"><xsl:value-of select="."/><xsl:text> </xsl:text></xsl:for-each>;<xsl:if test="$featureAtt/retired"><xsl:choose><xsl:when test="$featureAtt/taggedValue[@tag='AAA:GueltigBis']"><xsl:value-of select="$featureAtt/taggedValue[@tag='AAA:GueltigBis'][1]"/></xsl:when><xsl:otherwise><xsl:text>Ja</xsl:text></xsl:otherwise></xsl:choose></xsl:if>;<xsl:value-of select="$featureAtt/cardinality"/>;<xsl:value-of select="$featureAtt/ValueDataType"/>;<xsl:value-of select="$featureAtt/letzteAenderungRevisionsnummer"/>;&#13;&#10;</xsl:otherwise>
							</xsl:choose>
						</xsl:for-each>
					</xsl:if>
					<xsl:if test="count(/FC_FeatureCatalogue/FC_RelationshipRole[attribute::id=$featuretype/characterizedBy/@idref]) >= 1">
						<xsl:for-each select="/FC_FeatureCatalogue/FC_RelationshipRole[attribute::id=$featuretype/characterizedBy/@idref]"><xsl:value-of select="$featuretype/name"/>;<xsl:value-of select="$featuretype/code"/>;<xsl:for-each select="$featuretype/modellart"><xsl:value-of select="."/><xsl:text> </xsl:text></xsl:for-each>;<xsl:for-each select="$featuretype/grunddatenbestand"><xsl:value-of select="."/><xsl:text> </xsl:text></xsl:for-each>;<xsl:for-each select="$featuretype/profil"><xsl:value-of select="."/><xsl:text> </xsl:text></xsl:for-each>;<xsl:if test="$featuretype/retired"><xsl:choose><xsl:when test="$featuretype/taggedValue[@tag='AAA:GueltigBis']"><xsl:value-of select="$featuretype/taggedValue[@tag='AAA:GueltigBis'][1]"/></xsl:when><xsl:otherwise><xsl:text>Ja</xsl:text></xsl:otherwise></xsl:choose></xsl:if>;<xsl:value-of select="$featuretype/bedeutung"/>;<xsl:value-of select="$featuretype/wirdTypisiertDurch"/>;<xsl:value-of select="$featuretype/nutzungsart"/>;<xsl:value-of select="$featuretype/nutzungsartkennung"/>;<xsl:value-of select="$featuretype/letzteAenderungRevisionsnummer"/>;;;;;;;;;;;;;;;;;;;<xsl:value-of select="./name"/>;<xsl:value-of select="./code"/>;<xsl:for-each select="./modellart"><xsl:value-of select="."/><xsl:text> </xsl:text></xsl:for-each>;<xsl:for-each select="./grunddatenbestand"><xsl:value-of select="."/><xsl:text> </xsl:text></xsl:for-each>;<xsl:for-each select="./profil"><xsl:value-of select="."/><xsl:text> </xsl:text></xsl:for-each>;<xsl:if test="./retired"><xsl:choose><xsl:when test="./taggedValue[@tag='AAA:GueltigBis']"><xsl:value-of select="./taggedValue[@tag='AAA:GueltigBis'][1]"/></xsl:when><xsl:otherwise><xsl:text>Ja</xsl:text></xsl:otherwise></xsl:choose></xsl:if>;<xsl:value-of select="./cardinality"/>;<xsl:value-of select="./FeatureTypeIncluded/@name"/>;<xsl:value-of select="./letzteAenderungRevisionsnummer"/>;&#13;&#10;</xsl:for-each>
					</xsl:if>
				</xsl:for-each>
			</xsl:if>
		</xsl:for-each>
	</xsl:template>
</xsl:stylesheet>